version: 2

updates:
  - package-ecosystem: cargo
    directories:
      - /
      - /variants
      - /derive
      - /macros
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /variants
    schedule:
      interval: weekly
