[workspace]
default-members = ["variants"]
members = [
  "derive",
  "macros",
  "variants",
]
resolver = "3"

[workspace.package]
authors = [
  "FL03 <joe@pzzld.org> (https://github.com/FL03)"
]
categories = []
description = "Useful interfaces and macros for working with enums in Rust."
edition = "2024"
homepage = "https://github.com/FL03/variants/wiki"
keywords = ["derive", "enum", "macro", "rust", "variants"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/FL03/variants.git"
rust-version = "1.85.0"
version = "0.0.2"

[workspace.dependencies]
# local
variants = { path = "variants", version = "0.0.2" }
variants-derive = { path = "derive", version = "0.0.2" }
variants-macros = { path = "macros", version = "0.0.2" }
# benchmarking
criterion = { features = ["plotters"], version = "0.7" }
# error handling
anyhow = { default-features = false, version = "1" }
thiserror = { default-features = false, version = "2" }
# serialization
serde = { default-features = false, features = ["derive"], version = "1" }
serde_derive = { default-features = false, version = "1" }

# ********* Profiles *********
[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = "thin"
opt-level = 2
overflow-checks = true
panic = "unwind"
rpath = false

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 0
overflow-checks = false
panic = "abort"
rpath = false
