name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ variants-derive ]
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ matrix.package }}
  publish:
    env:
      CRATE: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ github.event.repository.name }}